<?php
namespace Phphleb\Imageresizer\Src;

/** Internal helper for retaining embedded ICC bytes in PNG files. */
final class PngIcc
{
    const SIGNATURE = "\x89PNG\r\n\x1a\n";

    /**
     * Returns a valid PNG with the original ICC in an iCCP chunk, or false.
     * Keeps the encoded pixels and all unrelated metadata chunks unchanged.
     * Replaces iCCP and removes the mutually exclusive sRGB PNG marker.
     * This is needed because some ImageMagick builds rewrite sRGB ICC data.
     *
     * @param string $png PNG bytes generated by the image encoder.
     * @param string $icc Original ICC bytes obtained from the loaded image.
     * @return string|false
     */
    public static function embed($png, $icc)
    {
        if (!is_string($png) || !is_string($icc) || strlen($icc) < 128 ||
            substr($icc, 36, 4) !== 'acsp' || !function_exists('gzcompress') ||
            substr($png, 0, 8) !== self::SIGNATURE) return false;

        $compressed = gzcompress($icc, 6);
        if ($compressed === false) return false;
        $payload = "ICC Profile\x00\x00" . $compressed;
        if (strlen($payload) >= 4294967296) return false;
        $chunk = self::chunk('iCCP', $payload);

        $length = strlen($png);
        $offset = 8;
        $result = self::SIGNATURE;
        $headerSeen = false;
        $dataSeen = false;
        $endSeen = false;
        $originalIcc = null;
        $profileChunks = 0;
        $srgbChunks = 0;

        while ($offset + 12 <= $length) {
            $chunkSize = unpack('N', substr($png, $offset, 4))[1];
            if ($chunkSize > $length - $offset - 12) return false;
            $type = substr($png, $offset + 4, 4);
            $rawChunk = substr($png, $offset, $chunkSize + 12);
            $offset += $chunkSize + 12;

            if (!$headerSeen) {
                if ($type !== 'IHDR' || $chunkSize !== 13) return false;
                $headerSeen = true;
                // The iCCP chunk must precede PLTE and IDAT.
                $result .= $rawChunk . $chunk;
                continue;
            }
            if ($type === 'IHDR') return false;
            if ($type === 'IDAT') $dataSeen = true;
            if ($type === 'sRGB') $srgbChunks++;
            if ($type === 'iCCP') {
                $profileChunks++;
                $data = substr($rawChunk, 8, $chunkSize);
                $separator = strpos($data, "\x00");
                if ($separator !== false && isset($data[$separator + 1]) &&
                    ord($data[$separator + 1]) === 0) {
                    $existing = @gzuncompress(substr($data, $separator + 2));
                    if (is_string($existing)) $originalIcc = $existing;
                }
            }
            if ($type !== 'iCCP' && $type !== 'sRGB') $result .= $rawChunk;
            if ($type === 'IEND') {
                $endSeen = $chunkSize === 0 && $offset === $length;
                break;
            }
        }
        if (!$headerSeen || !$dataSeen || !$endSeen) return false;
        // Avoid rewriting an already valid file; the original compression and
        // other metadata must remain byte-for-byte intact when possible.
        return $profileChunks === 1 && $srgbChunks === 0 && $originalIcc === $icc
            ? $png : $result;
    }

    /** Build a PNG chunk with its CRC-32 checksum. */
    private static function chunk($type, $data): string
    {
        return pack('N', strlen($data)) . $type . $data . pack('N', crc32($type . $data));
    }
}
